<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>annotations</Nullable>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Core", ""))</RootNamespace>

		<PackageId>Joce.EasyTool.Image</PackageId>
		<Authors>一个大西瓜,TimChen</Authors>
		<Version>1.2.0</Version>
		<Description>
			A open source C# tool to make .NET easy
		</Description>
		<PackageTags>Tool Power</PackageTags>
		<RepositoryUrl>https://github.com/dotnet-easy/easytool</RepositoryUrl>
		<PackageProjectUrl>https://easy-dotnet.com</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SkiaSharp" />
		<PackageReference Include="System.Drawing.Common" />
	</ItemGroup>

</Project>