<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>annotations</Nullable>
		<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".EmitMapper", ""))</RootNamespace>

		<PackageId>Joce.EasyTool.EmitMapper</PackageId>
		<Authors>Joce</Authors>
		<Description>
			EasyTool 对象映射扩展 - 基于EmitMapper的高性能对象映射工具，支持批量映射和自定义映射规则
		</Description>
		<PackageTags>Tool EmitMapper Mapper ObjectMapping</PackageTags>
		<RepositoryUrl>https://github.com/li761747705/easytool</RepositoryUrl>
		<PackageProjectUrl>https://github.com/li761747705/easytool</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageIcon>logo.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EmitMapper.Core" />
	</ItemGroup>

</Project>