<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
			<TargetFramework>netstandard2.1</TargetFramework>
			<Nullable>annotations</Nullable>
			<LangVersion>latest</LangVersion>
			<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Web", ""))</RootNamespace>

			<PackageId>Joce.EasyTool.Web</PackageId>
			<Authors>一个大西瓜,TimChen</Authors>
			<Description>
				EasyTool Web扩展 - ASP.NET Core TypeScript代码生成工具，自动扫描API Controller生成TypeScript类型定义和HTTP客户端代码
			</Description>
			<PackageTags>Tool Web TypeScript ASP.NET Core API CodeGeneration</PackageTags>
			<RepositoryUrl>https://github.com/dotnet-easy/easytool</RepositoryUrl>
			<PackageProjectUrl>https://easy-dotnet.com</PackageProjectUrl>
			<PackageReadmeFile>README.md</PackageReadmeFile>
			<PackageLicenseFile>LICENSE</PackageLicenseFile>
			<PackageIcon>logo.png</PackageIcon>
		</PropertyGroup>

		<ItemGroup>
			<None Include="..\LICENSE">
				<Pack>True</Pack>
				<PackagePath>\</PackagePath>
			</None>
			<None Include="..\README.md">
				<Pack>True</Pack>
				<PackagePath>\</PackagePath>
			</None>
			<None Include="..\logo.png">
				<Pack>True</Pack>
				<PackagePath>\</PackagePath>
			</None>
		</ItemGroup>

		<ItemGroup>
			<PackageReference Include="System.ComponentModel.Annotations" />
			<PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" />
			<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
		</ItemGroup>
	</Project>
